title: Muhammad Nizar Hamzah Al Faris
logo: https://media.licdn.com/dms/image/C5603AQHj4jWQ6WzDqQ/profile-displayphoto-shrink_800_800/0/1517408376882?e=1728518400&v=beta&t=_6LrjvcZ7Yy3ebnMwZoyTLZne6Ic07uvS8tJk3s8bt8
description: Chemical Engineer | Data Analyst Enthusiast
show_download: True


theme: jekyll-theme-Primer


