title: <font size: 5, color:'brown'>Muhammad Nizar Hamzah Al Faris</font>
logo: ./Image/circle.png
description: Chemical Engineer | Data Analyst Enthusiast
show_downloads: True


theme: jekyll-theme-minimal


