title: Muhammad Nizar Hamzah Al Faris
logo: ./Image/circle.png
description: Chemical Engineer | Data Analyst Enthusiast
<br>Find me on [LinkedIn](https://www.linkedin.com/in/muhammad-nizar-hamzah-al-faris-9a61a3108/)
show_downloads: True


theme: jekyll-theme-minimal


